[Logging]
	#
	############################################
	#
	#Default: false
	#-------------------------------------------
	"Boolean: Send All Changes To Chat" = false
[Ageing]
	#
	############################################
	#
	#Default: 800
	#-------------------------------------------
	#Range: 0 ~ 1000
	"Integer: Ageing Chance" = 5
["Social Trails"]
	#
	############################################
	#
	#Default: 1.0
	#-------------------------------------------
	#Range: 0.0 ~ 1000.0
	"Float: Trail Softening Modifier" = 10.0
	#
	############################################
	#
	#Default: true
	#-------------------------------------------
	"Boolean: Sneaking Prevents Trail Formation" = true
	#
	############################################
	#
	#Default: 700
	#-------------------------------------------
	#Range: 0 ~ 1000
	"Integer: Ground Erosion Chance" = 70
["Fluid Erosion"]
	#
	############################################
	#
	#Default: 800
	#-------------------------------------------
	#Range: 0 ~ 1000
	"Integer: Fluid Erosion Chance" = 10

