#Hard disable entire modules. Use at your own risk and don't ask for support if you use this. Write modid = false to disable modules
#Fri Oct 02 10:43:48 MSK 2026
a=false
another_furniture=true
backpacked=true
create=true
farmersdelight=true
friendsandfoes=true
hearth_and_home=true
quark=true
regions_unexplored=true
valhelsia_furniture=true
valhelsia_structures=true
